### ISSUE TITLE
Outdated usage example in README.md

### ISSUE THREAD

**Issue by esuomi** [entur/netex-validator-java#249]
Hi,

We use this validator as part of [Fintraffic's Validation and conversion service](https://www.fintraffic.fi/en/digitalservices/Traffic-and-Public-Transport-Data-Services/validation-and-conversion-service) and the recent major update broke compatability. This is not an issue, that's why you did it as major release and that's fine, but we are now lacking documentation on how to run the latest version and what is required to do so, which is blocking us from updating the dependency from 3.0.9 to 4.x on our side.

**Comment by vpaturet** [comment]
H,i and thank you for the feedback!

You're right, the documentation and examples are outdated, we will update them.
Please note that versions 3.x and 4.x are the groundwork for implementing new validation rules, but they do not contain any improvements or new features for end users, and we are still exploring other potentially breaking changes in the API. I guess this you should have been better communicated.

Of course you're welcome to test these versions, but  you might as well want to wait for a  release that actually adds new validation rules. We are hopefully not too far from that.

**Comment by vpaturet** [comment]
The example is now updated in the README file, and an executable demo (Demo.java) has been added.
The example does not illustrate yet the use of the new types of validator (JAXB-based file validators and dataset-wide validators).
This will be done when we promote these validators from Antu to netex-validator-java

**Comment by esuomi** [comment]
@vpaturet Excellent, thank you!

For use we can stick to 3.x versions as well if you're doing the Winamp thing where 5.x will be the "new new" version, so no need to stress too badly about this - this was notified by us because we use Dependabot which was a bit too excited to update the dependency (we usually do minor updates only), which lead me here.

Anyway, as this was fixed by #250, I'm happy with this for now, so closing.
